[tool.poetry]
name = "the-butler"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.0.1"
flask = "^1.1.2"
psutil = "^5.7.3"
tinydb = "^4.3.0"
bs4 = "^0.0.1"
pytz = "^2020.4"
pandas = "^1.1.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
