[tool.poetry]
name = "the-butler"
version = "0.1.0"
description = ""
authors = ["Harsh <hdadhich01@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.2"
psutil = "^5.7.3"
tinydb = "^4.3.0"
bs4 = "^0.0.1"
pytz = "^2020.4"
pandas = "^1.1.5"
ordinal = "^1.0.3"
bitlyshortener = "^0.5.1"
portolan = "^1.0.1"
emoji = "^1.2.0"
html2text = "^2020.1.16"
discord = "^1.0.1"
art = "^5.1"
humanize = "^3.3.0"
luxand = "^0.7"
clarifai-grpc = "^7.3.0"
"discord.py" = "^1.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
